---
name: Bug report
about: Create a report to help us improve
title: "[BUG] "
# Test this when https://github.com/go-gitea/gitea/issues/17877 gets fixed
# labels: ''
# assignees: ''

---
<!-- Please don't delete this template or we'll close your issue -->

- [ ] I have read and understood the [FAQ](https://gitea.ksol.io/karolyi/py3-validate-email/src/branch/master/FAQ.md)

**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:

**My debug output**

Output from the debug run described in the FAQ:

**Expected behavior**

A clear and concise description of what you expected to happen.

**Please complete the following information:**
 - OS: [e.g. Linux, FreeBSD, Windows]
 - Flavor and Version [e.g. Debian 22, FreeBSD 12.2]
 - Your network environment (ISP provided home connecton, or testing from an actual whitelisted server)
 - Your exact `py3-validate-email` module version

**Additional context**

Add any other context about the problem here.
